export type FrenchPartsOfSpeech = keyof typeof wordListFr;

export const wordListFr = {
  noun: [
    { word: "acteur", categories: ["profession"], genre: "M" },
    { word: "actrice", categories: ["profession"], genre: "F" },
    { word: "adolescent", categories: ["personnes", "famille"], genre: "M" },
    { word: "adolescente", categories: ["personnes", "famille"], genre: "F" },
    { word: "aeroport", categories: ["transport"], genre: "M" },
    { word: "agriculteur", categories: ["profession"], genre: "M" },
    { word: "agricultrice", categories: ["profession"], genre: "F" },
    { word: "aiguille", categories: ["objet"], genre: "F" },
    { word: "alligator", categories: ["animaux"], genre: "M" },
    { word: "ambulance", categories: ["sante"], genre: "F" },
    { word: "animal", categories: ["animaux"], genre: "M" },
    { word: "appareil-photo", categories: ["objet"], genre: "M" },
    { word: "apres-midi", categories: ["heure"], genre: "F" },
    { word: "arc-en-ciel", categories: ["science"], genre: "M" },
    { word: "architecte", categories: ["profession"], genre: "M" },
    { word: "architecte", categories: ["profession"], genre: "F" },
    { word: "armee", categories: ["choses"], genre: "F" },
    { word: "artiste", categories: ["profession"], genre: "M" },
    { word: "artiste", categories: ["profession"], genre: "F" },
    { word: "assurance", categories: ["choses"], genre: "F" },
    { word: "aube", categories: ["heure"], genre: "F" },
    { word: "aubergine", categories: ["alimentation"], genre: "F" },
    { word: "aurore", categories: ["temps"], genre: "F" },
    { word: "australie", categories: ["lieu"], genre: "F" },
    { word: "auteur", categories: ["profession"], genre: "M" },
    { word: "autrice", categories: ["profession"], genre: "F" },
    { word: "automne", categories: ["temps"], genre: "M" },
    { word: "avocat", categories: ["profession"], genre: "M" },
    { word: "avocate", categories: ["profession"], genre: "F" },
    { word: "baleine", categories: ["animaux"], genre: "F" },
    { word: "ballon", categories: ["choses"], genre: "M" },
    { word: "banane", categories: ["nourriture"], genre: "F" },
    { word: "barbe", categories: ["choses"], genre: "F" },
    { word: "barista", categories: ["profession"], genre: "M" },
    { word: "barista", categories: ["profession"], genre: "F" },
    { word: "batterie", categories: ["objet"], genre: "F" },
    { word: "bebe", categories: ["personnes", "famille"], genre: "M" },
    { word: "belgique", categories: ["lieu"], genre: "F" },
    { word: "belier", categories: ["choses", "technologie"], genre: "M" },
    { word: "bibliothecaire", categories: ["profession"], genre: "M" },
    { word: "bibliothecaire", categories: ["profession"], genre: "F" },
    { word: "bibliotheque", categories: ["lieu"], genre: "F" },
    { word: "bijou", categories: ["choses"], genre: "M" },
    { word: "bit", categories: ["choses", "technologie"], genre: "M" },
    { word: "botte", categories: ["choses"], genre: "F" },
    { word: "boucher", categories: ["profession"], genre: "M" },
    { word: "bouchere", categories: ["profession"], genre: "F" },
    { word: "bougie", categories: ["choses"], genre: "F" },
    { word: "boulanger", categories: ["profession"], genre: "M" },
    { word: "boulangere", categories: ["profession"], genre: "F" },
    { word: "branche", categories: ["choses"], genre: "F" },
    { word: "briquet", categories: ["objet"], genre: "M" },
    { word: "brosse-a-dents", categories: ["choses"], genre: "F" },
    { word: "homme-d-affaire", categories: ["personnes", "affaires"], genre: "M" },
    { word: "femme-d-affaire", categories: ["personnes", "affaires"], genre: "F" },
    { word: "cafe", categories: ["lieu"], genre: "M" },
    { word: "camion", categories: ["objet", "transport"], genre: "M" },
    { word: "caravane", categories: ["transport"], genre: "F" },
    { word: "carnet", categories: ["objet"], genre: "M" },
    { word: "carte-mere", categories: ["choses", "technologie"], genre: "F" },
    { word: "casque", categories: ["objet"], genre: "M" },
    { word: "cerf-volant", categories: ["choses"], genre: "M" },
    { word: "chacal", categories: ["animaux"], genre: "M" },
    { word: "chambre", categories: ["lieu"], genre: "F" },
    { word: "charpentier", categories: ["profession"], genre: "M" },
    { word: "charpentiere", categories: ["profession"], genre: "F" },
    { word: "chat", categories: ["animaux"], genre: "M" },
    { word: "chaussure", categories: ["objet"], genre: "M" },
    { word: "chef", categories: ["profession"], genre: "M" },
    { word: "cheffe", categories: ["profession"], genre: "F" },
    { word: "cheval", categories: ["animaux"], genre: "M" },
    { word: "chevelure", categories: ["choses"], genre: "F" },
    { word: "chien", categories: ["animaux"], genre: "M" },
    { word: "chine", categories: ["lieu"], genre: "F" },
    { word: "clavier", categories: ["choses", "technologie"], genre: "M" },
    { word: "coiffeur", categories: ["profession"], genre: "M" },
    { word: "coiffeuse", categories: ["profession"], genre: "F" },
    { word: "comptable", categories: ["profession"], genre: "M" },
    { word: "comptable", categories: ["profession"], genre: "F" },
    { word: "continent", categories: ["lieu"], genre: "M" },
    { word: "controleur", categories: ["choses", "technologie"], genre: "M" },
    { word: "coucher-de-soleil", categories: ["heure"], genre: "M" },
    { word: "couteau", categories: ["objet"], genre: "M" },
    { word: "cpu", categories: ["choses", "technologie"], genre: "M" },
    { word: "crayon", categories: ["choses", "education", "objet"], genre: "M" },
    { word: "crepuscule", categories: ["temps", "heure"], genre: "M" },
    { word: "criquet", categories: ["animaux"], genre: "M" },
    { word: "cuillere", categories: ["choses"], genre: "F" },
    { word: "cuir", categories: ["objet"], genre: "M" },
    { word: "cuisine", categories: ["lieu"], genre: "F" },
    { word: "danemark", categories: ["lieu"], genre: "M" },
    { word: "dejeuner", categories: ["nourriture"], genre: "M" },
    { word: "dentiste", categories: ["profession"], genre: "M" },
    { word: "dentiste", categories: ["profession"], genre: "F" },
    { word: "dessin-anime", categories: ["media"], genre: "M" },
    { word: "diamant", categories: ["objet"], genre: "M" },
    { word: "diner", categories: ["nourriture"], genre: "M" },
    { word: "drapeau", categories: ["choses"], genre: "M" },
    { word: "ecole", categories: ["education"], genre: "F" },
    { word: "ecrivain", categories: ["transport"], genre: "M" },
    { word: "ecrivaine", categories: ["transport"], genre: "F" },
    { word: "eglise", categories: ["religion"], genre: "F" },
    { word: "egypte", categories: ["lieu"], genre: "F" },
    { word: "electricien", categories: ["profession"], genre: "M" },
    { word: "elephant", categories: ["animaux"], genre: "M" },
    { word: "energie", categories: ["choses"], genre: "M" },
    { word: "enfant", categories: ["personnes", "famille"], genre: "M" },
    { word: "essence", categories: ["transport"], genre: "F" },
    { word: "etat", categories: ["lieu"], genre: "M" },
    { word: "ete", categories: ["temps"], genre: "M" },
    { word: "etudiant", categories: ["personnes", "education"], genre: "M" },
    { word: "etudiante", categories: ["personnes", "education"], genre: "F" },
    { word: "exabyte", categories: ["choses", "technologie"], genre: "M" },
    { word: "facteur", categories: ["profession"], genre: "M" },
    { word: "factrice", categories: ["profession"], genre: "F" },
    { word: "famille", categories: ["famille"], genre: "F" },
    { word: "fantome", categories: ["choses"], genre: "M" },
    { word: "femme", categories: ["personnes"], genre: "F" },
    { word: "fenetre", categories: ["choses"], genre: "F" },
    { word: "fer", categories: ["science"], genre: "M" },
    { word: "fil", categories: ["objet"], genre: "M" },
    { word: "fille", categories: ["famille", "personnes"], genre: "F" },
    { word: "finlande", categories: ["lieu"], genre: "F" },
    { word: "fleur", categories: ["objet"], genre: "F" },
    { word: "fleuriste", categories: ["profession"], genre: "M" },
    { word: "fleuriste", categories: ["profession"], genre: "F" },
    { word: "fontaine", categories: ["choses"], genre: "F" },
    { word: "football", categories: ["sports"], genre: "M" },
    { word: "foret", categories: ["lieu"], genre: "M" },
    { word: "foule", categories: ["personnes"], genre: "F" },
    { word: "france", categories: ["lieu"], genre: "F" },
    { word: "frere", categories: ["famille"], genre: "M" },
    { word: "fusee", categories: ["science"], genre: "F" },
    { word: "garage", categories: ["lieu"], genre: "M" },
    { word: "garcon", categories: ["personnes"], genre: "M" },
    { word: "gelee", categories: ["nourriture"], genre: "F" },
    { word: "gigaoctet", categories: ["choses", "technologie"], genre: "M" },
    { word: "glace", categories: ["science"], genre: "F" },
    { word: "gpu", categories: ["choses", "technologie"], genre: "M" },
    { word: "grand-mere", categories: ["personnes", "famille"], genre: "F" },
    { word: "grece", categories: ["lieu"], genre: "F" },
    { word: "guitare", categories: ["choses"], genre: "F" },
    { word: "hamburger", categories: ["nourriture"], genre: "M" },
    { word: "helicoptere", categories: ["transport"], genre: "M" },
    { word: "herbe", categories: ["choses"], genre: "F" },
    { word: "hiver", categories: ["temps"], genre: "M" },
    { word: "homme", categories: ["people"], genre: "M" },
    { word: "hopital", categories: ["lieu"], genre: "M" },
    { word: "huitre", categories: ["animaux"], genre: "F" },
    { word: "hydrogene", categories: ["science"], genre: "M" },
    { word: "ile", categories: ["lieu"], genre: "F" },
    { word: "impermeable", categories: ["choses"], genre: "M" },
    { word: "imprimante", categories: ["choses", "technologie"], genre: "F" },
    { word: "infirmier", categories: ["profession"], genre: "M" },
    { word: "infirmiere", categories: ["profession"], genre: "F" },
    { word: "ingenieur", categories: ["profession"], genre: "M" },
    { word: "ingenieure", categories: ["profession"], genre: "F" },
    { word: "insecte", categories: ["animaux"], genre: "M" },
    { word: "jardin", categories: ["nourriture"], genre: "M" },
    { word: "jordanie", categories: ["lieu"], genre: "F" },
    { word: "journaliste", categories: ["profession"], genre: "M" },
    { word: "journaliste", categories: ["profession"], genre: "F" },
    { word: "joystick", categories: ["choses", "technologie"], genre: "M" },
    { word: "juge", categories: ["profession"], genre: "M" },
    { word: "juge", categories: ["profession"], genre: "F" },
    { word: "jus", categories: ["nourriture"], genre: "M" },
    { word: "kangourou", categories: ["animaux"], genre: "M" },
    { word: "kilobyte", categories: ["choses", "technologie"], genre: "M" },
    { word: "lampe", categories: ["objet"], genre: "F" },
    { word: "legume", categories: ["nourriture"], genre: "M" },
    { word: "lezard", categories: ["animaux"], genre: "M" },
    { word: "lion", categories: ["animaux"], genre: "M" },
    { word: "lit", categories: ["choses"], genre: "M" },
    { word: "livre", categories: ["choses", "education"], genre: "M" },
    { word: "loup", categories: ["animaux"], genre: "M" },
    { word: "machine", categories: ["science"], genre: "F" },
    { word: "magazine", categories: ["medias"], genre: "M" },
    { word: "magicien", categories: ["people"], genre: "M" },
    { word: "magicienne", categories: ["people"], genre: "F" },
    { word: "maison", categories: ["lieu"], genre: "F" },
    { word: "maitre-nageur", categories: ["profession"], genre: "M" },
    { word: "maitre-nageuse", categories: ["profession"], genre: "F" },
    { word: "maladie", categories: ["choses"], genre: "F" },
    { word: "manteau", categories: ["objet"], genre: "M" },
    { word: "marche", categories: ["lieu"], genre: "M" },
    { word: "match", categories: ["choses"], genre: "M" },
    { word: "matin", categories: ["temps"], genre: "M" },
    { word: "mecanicien", categories: ["profession"], genre: "M" },
    { word: "mecanicienne", categories: ["profession"], genre: "F" },
    { word: "medecin", categories: ["profession"], genre: "M" },
    { word: "medecin", categories: ["profession"], genre: "F" },
    { word: "megaoctet", categories: ["choses", "technologie"], genre: "M" },
    { word: "memoire", categories: ["choses", "technologie"], genre: "F" },
    { word: "mere", categories: ["personnes", "famille"], genre: "F" },
    { word: "meuble", categories: ["objet"], genre: "M" },
    { word: "microphone", categories: ["choses"], genre: "M" },
    { word: "midi", categories: ["heure"], genre: "M" },
    { word: "miel", categories: ["nourriture"], genre: "M" },
    { word: "ministre", categories: ["personnes", "religion"], genre: "M" },
    { word: "ministre", categories: ["personnes", "religion"], genre: "F" },
    { word: "minuit", categories: ["heure"], genre: "M" },
    { word: "moniteur", categories: ["choses", "technologie"], genre: "M" },
    { word: "mort", categories: ["choses"], genre: "F" },
    { word: "mur", categories: ["objet"], genre: "M" },
    { word: "musicien", categories: ["profession"], genre: "M" },
    { word: "musicienne", categories: ["profession"], genre: "F" },
    { word: "nid", categories: ["objet"], genre: "M" },
    { word: "nigeria", categories: ["lieu"], genre: "M" },
    { word: "nourrisson", categories: ["personnes", "famille"], genre: "M" },
    { word: "nuit", categories: ["temps"], genre: "F" },
    { word: "ocean", categories: ["lieu"], genre: "M" },
    { word: "octet", categories: ["choses", "technologie"], genre: "M" },
    { word: "oeil", categories: ["choses"], genre: "M" },
    { word: "oeuf", categories: ["alimentation"], genre: "M" },
    { word: "oiseau", categories: ["animaux"], genre: "M" },
    { word: "ongle", categories: ["choses"], genre: "M" },
    { word: "opticien", categories: ["profession"], genre: "M" },
    { word: "opticienne", categories: ["profession"], genre: "F" },
    { word: "or", categories: ["choses"], genre: "M" },
    { word: "orange", categories: ["nourriture"], genre: "F" },
    { word: "ordinateur-portable", categories: ["objet", "technologie"], genre: "M" },
    { word: "ordinateur", categories: ["choses", "technologie"], genre: "M" },
    { word: "oreiller", categories: ["objet"], genre: "M" },
    { word: "ouganda", categories: ["lieu"], genre: "M" },
    { word: "ours", categories: ["animaux"], genre: "M" },
    { word: "oxygene", categories: ["science"], genre: "M" },
    { word: "pager", categories: ["choses", "technologie"], genre: "M" },
    { word: "paques", categories: ["religion"], genre: "F" },
    { word: "parapluie", categories: ["objet"], genre: "M" },
    { word: "parc", categories: ["lieu"], genre: "M" },
    { word: "pays", categories: ["lieu"], genre: "M" },
    { word: "peintre", categories: ["profession"], genre: "M" },
    { word: "peintre", categories: ["profession"], genre: "F" },
    { word: "peinture", categories: ["media"], genre: "F" },
    { word: "pere", categories: ["personnes", "famille"], genre: "M" },
    { word: "perroquet", categories: ["animaux"], genre: "M" },
    { word: "petaoctet", categories: ["choses", "technologie"], genre: "M" },
    { word: "petit-dejeuner", categories: ["choses"], genre: "M" },
    { word: "petrole", categories: ["objet"], genre: "M" },
    { word: "pharmacien", categories: ["profession"], genre: "M" },
    { word: "pharmacienne", categories: ["profession"], genre: "F" },
    { word: "photographe", categories: ["profession"], genre: "M" },
    { word: "photographe", categories: ["profession"], genre: "F" },
    { word: "piano", categories: ["choses"], genre: "M" },
    { word: "pierre", categories: ["choses"], genre: "F" },
    { word: "pilote", categories: ["profession"], genre: "M" },
    { word: "pilote", categories: ["profession"], genre: "F" },
    { word: "pizza", categories: ["nourriture"], genre: "F" },
    { word: "plage", categories: ["lieu"], genre: "F" },
    { word: "planete", categories: ["science"], genre: "F" },
    { word: "plastique", categories: ["choses"], genre: "M" },
    { word: "plombier", categories: ["profession"], genre: "M" },
    { word: "plombiere", categories: ["profession"], genre: "F" },
    { word: "pluie", categories: ["choses"], genre: "F" },
    { word: "plume", categories: ["choses"], genre: "F" },
    { word: "poisson", categories: ["animaux"], genre: "M" },
    { word: "policier", categories: ["profession"], genre: "M" },
    { word: "policiere", categories: ["profession"], genre: "F" },
    { word: "pomme-de-terre", categories: ["nourriture"], genre: "F" },
    { word: "pomme", categories: ["nourriture"], genre: "F" },
    { word: "pompier", categories: ["profession"], genre: "M" },
    { word: "pompiere", categories: ["profession"], genre: "F" },
    { word: "portugais", categories: ["lieu"], genre: "M" },
    { word: "printemps", categories: ["temps"], genre: "M" },
    { word: "processeur", categories: ["choses", "technologie"], genre: "M" },
    { word: "professeur", categories: ["personnes", "education", "profession"], genre: "M" },
    { word: "professeure", categories: ["personnes", "education", "profession"], genre: "F" },
    { word: "psychiatre", categories: ["profession"], genre: "M" },
    { word: "psychiatre", categories: ["profession"], genre: "F" },
    { word: "publicite", categories: ["medias"], genre: "F" },
    { word: "receptionniste", categories: ["profession"], genre: "M" },
    { word: "receptionniste", categories: ["profession"], genre: "F" },
    { word: "refrigerateur", categories: ["nourriture"], genre: "M" },
    { word: "reine", categories: ["personnes"], genre: "F" },
    { word: "reponse", categories: ["choses"], genre: "F" },
    { word: "repos", categories: ["choses"], genre: "M" },
    { word: "restaurant", categories: ["lieu"], genre: "M" },
    { word: "reve", categories: ["choses"], genre: "M" },
    { word: "riviere", categories: ["choses"], genre: "F" },
    { word: "robe", categories: ["choses"], genre: "F" },
    { word: "roi", categories: ["personnes"], genre: "M" },
    { word: "rose", categories: ["choses"], genre: "F" },
    { word: "russie", categories: ["lieu"], genre: "F" },
    { word: "sandwich", categories: ["nourriture"], genre: "M" },
    { word: "scientifique", categories: ["profession"], genre: "M" },
    { word: "scientifique", categories: ["profession"], genre: "F" },
    { word: "scooter", categories: ["transport"], genre: "M" },
    { word: "secretaire", categories: ["profession"], genre: "M" },
    { word: "secretaire", categories: ["profession"], genre: "F" },
    { word: "serrure", categories: ["choses"], genre: "F" },
    { word: "serveur", categories: ["profession"], genre: "M" },
    { word: "serveuse", categories: ["profession"], genre: "F" },
    { word: "serviette", categories: ["objet"], genre: "F" },
    { word: "shampooing", categories: ["objet"], genre: "M" },
    { word: "singe", categories: ["animaux"], genre: "M" },
    { word: "smartphone", categories: ["choses", "technologie"], genre: "M" },
    { word: "soiree", categories: ["heure"], genre: "F" },
    { word: "solstice", categories: ["temps"], genre: "M" },
    { word: "souris", categories: ["objet", "technologie", "animal"], genre: "F" },
    { word: "stagiaire", categories: ["profession"], genre: "M" },
    { word: "stagiaire", categories: ["profession"], genre: "F" },
    { word: "sucre", categories: ["nourriture"], genre: "M" },
    { word: "suedois", categories: ["lieu"], genre: "M" },
    { word: "table", categories: ["objet"], genre: "F" },
    { word: "tailleur", categories: ["profession"], genre: "M" },
    { word: "tapis", categories: ["objet"], genre: "M" },
    { word: "telephone", categories: ["choses"], genre: "M" },
    { word: "television", categories: ["media"], genre: "F" },
    { word: "tente", categories: ["choses"], genre: "F" },
    { word: "teraoctet", categories: ["choses", "technologie"], genre: "M" },
    { word: "thailande", categories: ["lieu"], genre: "F" },
    { word: "tigre", categories: ["animaux"], genre: "M" },
    { word: "tomate", categories: ["nourriture"], genre: "F" },
    { word: "traducteur", categories: ["profession"], genre: "M" },
    { word: "traductrice", categories: ["profession"], genre: "F" },
    { word: "trafic", categories: ["choses"], genre: "M" },
    { word: "train", categories: ["transport"], genre: "M" },
    { word: "van", categories: ["transport"], genre: "M" },
    { word: "vase", categories: ["objet"], genre: "M" },
    { word: "vautour", categories: ["animaux"], genre: "M" },
    { word: "veille", categories: ["heure"], genre: "F" },
    { word: "vendeur", categories: ["personnes", "affaires", "profession"], genre: "M" },
    { word: "vendeuse", categories: ["personnes", "affaires", "profession"], genre: "F" },
    { word: "verre", categories: ["choses"], genre: "M" },
    { word: "ville", categories: ["lieu"], genre: "F" },
    { word: "voiture", categories: ["transport"], genre: "F" },
    { word: "vr", categories: ["objet", "technologie"], genre: "F" },
    { word: "xylophone", categories: ["choses"], genre: "M" },
    { word: "yacht", categories: ["transport"], genre: "M" },
    { word: "yak", categories: ["animaux"], genre: "M" },
    { word: "yottabyte", categories: ["choses", "technologie"], genre: "M" },
    { word: "zebre", categories: ["animaux"], genre: "M" },
    { word: "zettaoctet", categories: ["choses", "technologie"], genre: "M" },
    { word: "zoo", categories: ["animaux"], genre: "M" },
  ] as const,
  adjective: [
    { word: "abondant", feminized: "abondante", categories: ["quantite"] },
    { word: "abordable", feminized: "abordable", categories: ["condition"] },
    { word: "acide", feminized: "acide", categories: ["gout"] },
    { word: "acidule", feminized: "acidulee", categories: ["gout"] },
    { word: "adorable", feminized: "adorable", categories: ["personnalite"] },
    { word: "agreable", feminized: "agreable", categories: ["personnalite"] },
    { word: "agressif", feminized: "agressive", categories: ["personnalite"] },
    { word: "aigre", feminized: "aigre", categories: ["gout"] },
    { word: "ambitieux", feminized: "ambitieuse", categories: ["personnalite"] },
    { word: "amer", feminized: "amere", categories: ["gout"] },
    { word: "ancien", feminized: "ancienne", categories: ["temps"] },
    { word: "assourdissant", feminized: "assourdissante", categories: ["sons"] },
    { word: "bas", feminized: "basse", categories: ["formes"] },
    { word: "beau", feminized: "belle", categories: ["apparence"] },
    { word: "elegant", feminized: "elegante", categories: ["apparence"] },
    { word: "beaucoup", feminized: "beaucoup", categories: ["quantite"] },
    { word: "bizarre", feminized: "bizarre", categories: ["condition"] },
    { word: "blanc", feminized: "blanche", categories: ["couleur"] },
    { word: "bleu", feminized: "bleue", categories: ["couleur"] },
    { word: "bossele", feminized: "bosselee", categories: ["toucher"] },
    { word: "bref", feminized: "breve", categories: ["temps"] },
    { word: "bruyant", feminized: "bruyante", categories: ["sons"] },
    { word: "calin", feminized: "caline", categories: ["toucher"] },
    { word: "calme", feminized: "calme", categories: ["personnalite"] },
    { word: "carre", feminized: "carree", categories: ["formes"] },
    { word: "celebre", feminized: "celebre", categories: ["condition"] },
    { word: "centaines", feminized: "centaines", categories: ["quantite"] },
    { word: "charnu", feminized: "charnue", categories: ["apparence"] },
    { word: "chaud", feminized: "chaude", categories: ["toucher", "gout"] },
    { word: "bouillant", feminized: "bouillante", categories: ["toucher"] },
    { word: "chauve", feminized: "chauve", categories: ["apparence"] },
    { word: "chetif", feminized: "chetive", categories: ["taille"] },
    { word: "chuchotant", feminized: "chuchotante", categories: ["sons"] },
    { word: "citron", feminized: "citron", categories: ["couleur"] },
    { word: "colerique", feminized: "colerique", categories: ["personnalite"] },
    { word: "collant", feminized: "collante", categories: ["toucher"] },
    { word: "colossal", feminized: "colossale", categories: ["taille"] },
    { word: "cool", feminized: "cool", categories: ["touch"] },
    { word: "courageux", feminized: "courageuse", categories: ["personnalite"] },
    { word: "courbe", feminized: "courbe", categories: ["formes"] },
    { word: "court", feminized: "courte", categories: ["taille", "apparence", "temps"] },
    { word: "cremeux", feminized: "cremeuse", categories: ["gout"] },
    { word: "creux", feminized: "creuse", categories: ["formes"] },
    { word: "criard", feminized: "criarde", categories: ["sons"] },
    { word: "debraille", feminized: "debraillee", categories: ["apparence"] },
    { word: "degoutant", feminized: "degoutante", categories: ["gout"] },
    { word: "delicieux", feminized: "delicieuse", categories: ["gout"] },
    { word: "dodu", feminized: "dodue", categories: ["apparence"] },
    { word: "doue", feminized: "douee", categories: ["condition"] },
    { word: "doux", feminized: "douce", categories: ["gout", "personnalite"] },
    { word: "droit", feminized: "droite", categories: ["formes"] },
    { word: "dur", feminized: "dure", categories: ["sons"] },
    { word: "eblouissant", feminized: "eblouissante", categories: ["apparence"] },
    { word: "echo", feminized: "echo", categories: ["sons"] },
    { word: "effrayant", feminized: "effrayante", categories: ["personnalite"] },
    { word: "elegant", feminized: "elegante", categories: ["apparence"] },
    { word: "embarrasse", feminized: "embarrassee", categories: ["personnalite"] },
    { word: "endommage", feminized: "endommagee", categories: ["toucher"] },
    { word: "enorme", feminized: "enorme", categories: ["taille"] },
    { word: "enthousiaste", feminized: "enthousiaste", categories: ["personnalite"] },
    { word: "epars", feminized: "eparse", categories: ["quantite"] },
    { word: "epice", feminized: "epicee", categories: ["gout"] },
    { word: "epineux", feminized: "epineuse", categories: ["toucher"] },
    { word: "etroit", feminized: "etroite", categories: ["formes"] },
    { word: "facile", feminized: "facile", categories: ["condition"] },
    { word: "faible", feminized: "faible", categories: ["sons", "toucher"] },
    { word: "fantasque", feminized: "fantasque", categories: ["apparence"] },
    { word: "farineux", feminized: "farineuse", categories: ["condition"] },
    { word: "feroce", feminized: "feroce", categories: ["personnalite"] },
    { word: "fidele", feminized: "fidele", categories: ["personnalite"] },
    { word: "fier", feminized: "fiere", categories: ["personnalite"] },
    { word: "flasque", feminized: "flasque", categories: ["apparence"] },
    { word: "floconneux", feminized: "floconneuse", categories: ["toucher"] },
    { word: "fondu", feminized: "fondue", categories: ["toucher"] },
    { word: "fort", feminized: "forte", categories: ["sons", "toucher"] },
    { word: "fracassant", feminized: "fracassante", categories: ["sons"] },
    { word: "frais", feminized: "fraiche", categories: ["gout"] },
    { word: "froid", feminized: "froide", categories: ["toucher"] },
    { word: "glace", feminized: "glacee", categories: ["toucher"] },
    { word: "futur", feminized: "future", categories: ["temps"] },
    { word: "gache", feminized: "gachee", categories: ["gout"] },
    { word: "galbe", feminized: "galbee", categories: ["apparence"] },
    { word: "geant", feminized: "geante", categories: ["taille"] },
    { word: "gele", feminized: "gelee", categories: ["toucher"] },
    { word: "gemissant", feminized: "gemissante", categories: ["sons"] },
    { word: "gentil", feminized: "gentille", categories: ["personnalite"] },
    { word: "gigantesque", feminized: "gigantesque", categories: ["taille"] },
    { word: "glacial", feminized: "glaciale", categories: ["toucher"] },
    { word: "glamour", feminized: "glamour", categories: ["apparence"] },
    { word: "gluant", feminized: "gluante", categories: ["toucher"] },
    { word: "grand", feminized: "grande", categories: ["taille"] },
    { word: "haut", feminized: "haute", categories: ["taille"] },
    { word: "gras", feminized: "grasse", categories: ["toucher", "gout"] },
    { word: "grincant", feminized: "grincante", categories: ["sons"] },
    { word: "grincheux", feminized: "grincheuse", categories: ["personnalite"] },
    { word: "gris", feminized: "grise", categories: ["couleur"] },
    { word: "gros", feminized: "grosse", categories: ["taille"] },
    { word: "hallucine", feminized: "hallucinee", categories: ["condition"] },
    { word: "haut", feminized: "haute", categories: ["formes"] },
    { word: "heureux", feminized: "heureuse", categories: ["personnalite"] },
    { word: "hirsute", feminized: "hirsute", categories: ["apparence", "toucher"] },
    { word: "humide", feminized: "humide", categories: ["toucher"] },
    { word: "mouille", feminized: "mouillee", categories: ["toucher"] },
    { word: "hurlant", feminized: "hurlante", categories: ["sons"] },
    { word: "immense", feminized: "immense", categories: ["taille"] },
    { word: "important", feminized: "importante", categories: ["condition"] },
    { word: "imposant", feminized: "imposante", categories: ["taille"] },
    { word: "impuissant", feminized: "impuissante", categories: ["personnalite"] },
    { word: "incalculable", feminized: "incalculable", categories: ["quantite"] },
    { word: "inegal", feminized: "inegale", categories: ["toucher"] },
    { word: "inesthetique", feminized: "inesthetique", categories: ["apparence"] },
    { word: "ininteresse", feminized: "ininteressee", categories: ["condition"] },
    { word: "inquiet", feminized: "inquiete", categories: ["personnalite"] },
    { word: "insignifiant", feminized: "insignifiante", categories: ["condition"] },
    { word: "insipide", feminized: "insipide", categories: ["gout"] },
    { word: "intelligent", feminized: "intelligente", categories: ["etat"] },
    { word: "irreflechi", feminized: "irreflechie", categories: ["personnalite"] },
    { word: "irritant", feminized: "irritante", categories: ["personnalite"] },
    { word: "jaloux", feminized: "jalouse", categories: ["personnalite"] },
    { word: "jaune", feminized: "jaune", categories: ["couleur"] },
    { word: "jeune", feminized: "jeune", categories: ["temps"] },
    { word: "joyeux", feminized: "joyeuse", categories: ["personnalite"] },
    { word: "juteux", feminized: "juteuse", categories: ["gout"] },
    { word: "lache", feminized: "lache", categories: ["toucher"] },
    { word: "large", feminized: "large", categories: ["formes", "taille"] },
    { word: "lent", feminized: "lente", categories: ["temps"] },
    { word: "limite", feminized: "limite", categories: ["quantite"] },
    { word: "long", feminized: "longue", categories: ["temps", "apparence"] },
    { word: "magnifique", feminized: "magnifique", categories: ["apparence"] },
    { word: "resplendissant", feminized: "resplendissante", categories: ["apparence"] },
    { word: "maigre", feminized: "maigre", categories: ["apparence", "formes", "taille"] },
    { word: "mince", feminized: "mince", categories: ["apparence", "formes", "taille"] },
    { word: "maladroit", feminized: "maladroite", categories: ["personnalite"] },
    { word: "marron", feminized: "marron", categories: ["couleur"] },
    { word: "massif", feminized: "massive", categories: ["taille"] },
    { word: "mauvais", feminized: "mauvaise", categories: ["condition"] },
    { word: "meilleur", feminized: "meilleure", categories: ["condition"] },
    { word: "melodique", feminized: "melodique", categories: ["sons"] },
    { word: "merveilleux", feminized: "merveilleuse", categories: ["personnalite"] },
    { word: "microscopique", feminized: "microscopique", categories: ["taille"] },
    { word: "milliards", feminized: "milliards", categories: ["quantite"] },
    { word: "milliers", feminized: "milliers", categories: ["quantite"] },
    { word: "millions", feminized: "millions", categories: ["quantite"] },
    { word: "miniature", feminized: "miniature", categories: ["taille"] },
    { word: "minuscule", feminized: "minuscule", categories: ["taille"] },
    { word: "moche", feminized: "moche", categories: ["apparence"] },
    { word: "moderne", feminized: "moderne", categories: ["temps"] },
    { word: "moisi", feminized: "moisie", categories: ["gout"] },
    { word: "mort", feminized: "morte", categories: ["etat"] },
    { word: "mou", feminized: "molle", categories: ["condition"] },
    { word: "mur", feminized: "mure", categories: ["gout"] },
    { word: "muscle", feminized: "musclee", categories: ["apparence"] },
    { word: "mysterieux", feminized: "mysterieuse", categories: ["personnalite"] },
    { word: "nerveux", feminized: "nerveuse", categories: ["personnalite"] },
    { word: "noir", feminized: "noire", categories: ["couleur"] },
    { word: "noisette", feminized: "noisette", categories: ["gout"] },
    { word: "nombreux", feminized: "nombreuse", categories: ["quantite"] },
    { word: "nutritif", feminized: "nutritive", categories: ["gout"] },
    { word: "obeissant", feminized: "obeissante", categories: ["personnalite"] },
    { word: "odieux", feminized: "odieuse", categories: ["personnalite"] },
    { word: "orange", feminized: "orange", categories: ["couleur"] },
    { word: "ordinaire", feminized: "ordinaire", categories: ["apparence"] },
    { word: "panique", feminized: "paniquee", categories: ["personnalite"] },
    { word: "paresseux", feminized: "paresseuse", categories: ["personnalite"] },
    { word: "pauvre", feminized: "pauvre", categories: ["condition"] },
    { word: "pelucheux", feminized: "pelucheuse", categories: ["toucher"] },
    { word: "perplexe", feminized: "perplexe", categories: ["personnalite"] },
    { word: "petit", feminized: "petite", categories: ["taille", "quantite"] },
    { word: "peu", feminized: "peu", categories: ["quantite"] },
    { word: "pitoyable", feminized: "pitoyable", categories: ["personnalite"] },
    { word: "pittoresque", feminized: "pittoresque", categories: ["apparence"] },
    { word: "plaintif", feminized: "plaintive", categories: ["sons"] },
    { word: "plat", feminized: "plate", categories: ["formes"] },
    { word: "plein", feminized: "pleine", categories: ["quantite"] },
    { word: "plus", feminized: "plus", categories: ["quantite"] },
    { word: "pointu", feminized: "pointue", categories: ["toucher"] },
    { word: "poli", feminized: "polie", categories: ["personnalite"] },
    { word: "pourri", feminized: "pourrie", categories: ["gout"] },
    { word: "precoce", feminized: "precoce", categories: ["temps"] },
    { word: "prehistorique", feminized: "prehistorique", categories: ["epoque"] },
    { word: "profond", feminized: "profonde", categories: ["formes"] },
    { word: "propre", feminized: "propre", categories: ["apparence"] },
    { word: "prudent", feminized: "prudente", categories: ["condition"] },
    { word: "puissant", feminized: "puissante", categories: ["condition"] },
    { word: "putride", feminized: "putride", categories: ["gout"] },
    { word: "raffine", feminized: "raffinee", categories: ["formes"] },
    { word: "raide", feminized: "raide", categories: ["formes"] },
    { word: "rance", feminized: "rance", categories: ["gout"] },
    { word: "rapide", feminized: "rapide", categories: ["temps"] },
    { word: "rappeur", feminized: "rappeuse", categories: ["sons"] },
    { word: "rare", feminized: "rare", categories: ["quantite"] },
    { word: "rassis", feminized: "rassise", categories: ["gout"] },
    { word: "rauque", feminized: "rauque", categories: ["sons"] },
    { word: "reconnaissant", feminized: "reconnaissante", categories: ["personnalite"] },
    { word: "repoussant", feminized: "repoussante", categories: ["personnalite"] },
    { word: "riche", feminized: "riche", categories: ["condition"] },
    { word: "rond", feminized: "ronde", categories: ["formes"] },
    { word: "ronronnant", feminized: "ronronnante", categories: ["sons"] },
    { word: "rouge", feminized: "rouge", categories: ["couleur"] },
    { word: "rugueux", feminized: "rugueuse", categories: ["toucher"] },
    { word: "rythme", feminized: "rythmee", categories: ["sons"] },
    { word: "sale", feminized: "sale", categories: ["gout", "toucher"] },
    { word: "saumon", feminized: "saumon", categories: ["couleur"] },
    { word: "sec", feminized: "seche", categories: ["toucher"] },
    { word: "seduisant", feminized: "seduisante", categories: ["apparence"] },
    { word: "serre", feminized: "serree", categories: ["toucher"] },
    { word: "sifflant", feminized: "sifflante", categories: ["sons"] },
    { word: "spirituel", feminized: "spirituelle", categories: ["personnalite"] },
    { word: "strident", feminized: "stridente", categories: ["sons"] },
    { word: "stupide", feminized: "stupide", categories: ["personnalite"] },
    { word: "substantiel", feminized: "substantielle", categories: ["quantite"] },
    { word: "sucre", feminized: "sucre", categories: ["gout"] },
    { word: "suffisant", feminized: "suffisante", categories: ["quantite"] },
    { word: "superficiel", feminized: "superficielle", categories: ["formes"] },
    { word: "svelte", feminized: "svelte", categories: ["apparence"] },
    { word: "sympa", feminized: "sympa", categories: ["personnalite"] },
    { word: "tardif", feminized: "tardive", categories: ["heure"] },
    { word: "tendre", feminized: "tendre", categories: ["etat"] },
    { word: "tendu", feminized: "tendue", categories: ["personnalite"] },
    { word: "terne", feminized: "terne", categories: ["apparence"] },
    { word: "timide", feminized: "timide", categories: ["etat"] },
    { word: "tintant", feminized: "tintante", categories: ["sons"] },
    { word: "tonitruant", feminized: "tonitruante", categories: ["sons"] },
    { word: "tordu", feminized: "tordue", categories: ["formes"] },
    { word: "tranquille", feminized: "tranquille", categories: ["sons"] },
    { word: "trapu", feminized: "trapue", categories: ["apparence"] },
    { word: "utile", feminized: "utile", categories: ["condition"] },
    { word: "vaincu", feminized: "vaincue", categories: ["personnalite"] },
    { word: "vaste", feminized: "vaste", categories: ["condition"] },
    { word: "venteux", feminized: "venteuse", categories: ["toucher"] },
    { word: "vert", feminized: "verte", categories: ["couleur"] },
    { word: "victorieux", feminized: "victorieuse", categories: ["personnalite"] },
    { word: "vieux", feminized: "vieille", categories: ["temps"] },
    { word: "vif", feminized: "vive", categories: ["personnalite"] },
    { word: "violet", feminized: "violette", categories: ["couleur"] },
    { word: "vivant", feminized: "vivante", categories: ["condition"] },
    { word: "zele", feminized: "zelee", categories: ["personnalite"] },
  ] as const,
};

export type FrenchWordList = typeof wordListFr;

export type FrenchCategories = {
  [K in keyof FrenchWordList]: FrenchWordList[K][number]["categories"][number];
};
